name: Reusable Deploy
on:
  workflow_call:
    inputs:
      artifact-name:
        description: The name of the deployable artifact files
        required: true
        type: string
    # secrets:
    #   some-secret:
    #     required: false
    outputs:
      result:
        value: ${{ jobs.deploy.outputs.outcome }}
jobs:
  deploy:
    outputs:
      outcome: ${{steps.set-result.outputs.step-result}}
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: dawidd6/action-download-artifact@v3.1.4
        with:
          name: ${{ inputs.artifact-name }}
      - name: List files
        run: ls
      - name: Deploy and upload
        run: echo "Deploying..."
      - name: Set output result
        id: set-result
        run: echo "step-result=success" >> $GITHUB_OUTPUT
